---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: kaniko-build
spec:
  taskRef:
    name: kaniko
  inputs:
    resources:
    - name: source
      resourceRef:
        name: app-sourcecode
  outputs:
    resources:
    - name: image
      resourceRef:
        name: demo-image
